### ISSUE TITLE
mixlib-archive-0.4.5/lib/mixlib/archive/tar.rb:138:in `reader': Unrecognized archive format (Mixlib::Archive::TarError)

### ISSUE THREAD

**Issue by AntonOfTheWoods** [chef/mixlib-archive#20]
Looks like 0.4.5 has a bug when being used by berks. 

`
$ bundle exec berks install
...
Installing yum-erlang_solutions (2.0.0)

Installing yum-mysql-community (4.0.1)

Installing yum-repoforge (3.0.0)

/home/a.melser/.rvm/gems/ruby-2.4.1/gems/mixlib-archive-0.4.5/lib/mixlib/archive/tar.rb:138:in `reader': Unrecognized archive format (Mixlib::Archive::TarError)
        from /home/a.melser/.rvm/gems/ruby-2.4.1/gems/mixlib-archive-0.4.5/lib/mixlib/archive/tar.rb:26:in `extract'
        from /home/a.melser/.rvm/gems/ruby-2.4.1/gems/mixlib-archive-0.4.5/lib/mixlib/archive.rb:47:in `extract'
        from /home/a.melser/.rvm/gems/ruby-2.4.1/gems/berkshelf-6.3.2/lib/berkshelf/community_rest.rb:16:in `unpack'
        from /home/a.melser/.rvm/gems/ruby-2.4.1/gems/berkshelf-6.3.2/lib/berkshelf/community_rest.rb:102:in `download'
        from /home/a.melser/.rvm/gems/ruby-2.4.1/gems/berkshelf-6.3.2/lib/berkshelf/downloader.rb:70:in `try_download'
        from /home/a.melser/.rvm/gems/ruby-2.4.1/gems/berkshelf-6.3.2/lib/berkshelf/downloader.rb:40:in `block in download'
        from /home/a.melser/.rvm/gems/ruby-2.4.1/gems/berkshelf-6.3.2/lib/berkshelf/downloader.rb:39:in `each'
        from /home/a.melser/.rvm/gems/ruby-2.4.1/gems/berkshelf-6.3.2/lib/berkshelf/downloader.rb:39:in `download'
        from /home/a.melser/.rvm/gems/ruby-2.4.1/gems/berkshelf-6.3.2/lib/berkshelf/installer.rb:108:in `install'
        from /home/a.melser/.rvm/gems/ruby-2.4.1/gems/berkshelf-6.3.2/lib/berkshelf/installer.rb:137:in `block (2 levels) in install_from_lockfile'
        from /home/a.melser/.rvm/gems/ruby-2.4.1/gems/concurrent-ruby-1.0.5/lib/concurrent/executor/safe_task_executor.rb:24:in `block in execute'
        from /home/a.melser/.rvm/gems/ruby-2.4.1/gems/concurrent-ruby-1.0.5/lib/concurrent/synchronization/mri_lockable_object.rb:38:in `block in synchronize'
        from /home/a.melser/.rvm/gems/ruby-2.4.1/gems/concurrent-ruby-1.0.5/lib/concurrent/synchronization/mri_lockable_object.rb:38:in `synchronize'
        from /home/a.melser/.rvm/gems/ruby-2.4.1/gems/concurrent-ruby-1.0.5/lib/concurrent/synchronization/mri_lockable_object.rb:38:in `synchronize'
        from /home/a.melser/.rvm/gems/ruby-2.4.1/gems/concurrent-ruby-1.0.5/lib/concurrent/executor/safe_task_executor.rb:19:in `execute'
        from /home/a.melser/.rvm/gems/ruby-2.4.1/gems/concurrent-ruby-1.0.5/lib/concurrent/ivar.rb:170:in `safe_execute'
        from /home/a.melser/.rvm/gems/ruby-2.4.1/gems/concurrent-ruby-1.0.5/lib/concurrent/future.rb:52:in `block in execute'
        from /home/a.melser/.rvm/gems/ruby-2.4.1/gems/concurrent-ruby-1.0.5/lib/concurrent/executor/ruby_thread_pool_executor.rb:348:in `run_task'
        from /home/a.melser/.rvm/gems/ruby-2.4.1/gems/concurrent-ruby-1.0.5/lib/concurrent/executor/ruby_thread_pool_executor.rb:337:in `block (3 levels) in create_worker'
        from /home/a.melser/.rvm/gems/ruby-2.4.1/gems/concurrent-ruby-1.0.5/lib/concurrent/executor/ruby_thread_pool_executor.rb:320:in `loop'
        from /home/a.melser/.rvm/gems/ruby-2.4.1/gems/concurrent-ruby-1.0.5/lib/concurrent/executor/ruby_thread_pool_executor.rb:320:in `block (2 levels) in create_worker'
        from /home/a.melser/.rvm/gems/ruby-2.4.1/gems/concurrent-ruby-1.0.5/lib/concurrent/executor/ruby_thread_pool_executor.rb:319:in `catch'
        from /home/a.melser/.rvm/gems/ruby-2.4.1/gems/concurrent-ruby-1.0.5/lib/concurrent/executor/ruby_thread_pool_executor.rb:319:in `block in create_worker'
`

**Comment by thommay** [comment]
What's your berksfile so i can try reproducing this?

**Comment by thommay** [comment]
Also I can't reproduce that with `yum-repoforge 3.0.0`; can you run `bundle exec berks install -d` please? Also also, you don't have libarchive or ffi-libarchive installed so this won't solve the problem most people are upgrading for.

**Comment by lbjay** [comment]
I am also seeing this. For me it seems to be failing on yum-epel, but I can't be certain. This is someone elses code/project that I'm trying to fix right now.

Berksfile:
```
source "https://supermarket.chef.io"

cookbook 'nfs', '~> 2.1.0'
cookbook 'apt', '~> 2.9.2'
cookbook 'cron', '~> 1.6.1'
cookbook 'nodejs', '~> 2.4.4'
cookbook 'activemq', '~> 2.0.4'
cookbook 'java', '1.47'
cookbook 'maven', '~> 2.2.0'

metadata
```

**Comment by spion06** [comment]
Also seeing this. an example of a berks that will break

```
source 'https://supermarket.chef.io'

cookbook 'cerner_splunk'
```

**Comment by skadz** [comment]
Seeing something similar when running a bundle

E, [2018-05-04T19:11:21.273709 #11212] ERROR -- : Actor crashed!
Mixlib::Archive::TarError: Unrecognized archive format
	/usr/local/bundle/gems/mixlib-archive-0.4.5/lib/mixlib/archive/tar.rb:138:in `reader'
	/usr/local/bundle/gems/mixlib-archive-0.4.5/lib/mixlib/archive/tar.rb:26:in `extract'
	/usr/local/bundle/gems/mixlib-archive-0.4.5/lib/mixlib/archive.rb:47:in `extract'
	/usr/local/bundle/gems/berkshelf-4.3.5/lib/berkshelf/community_rest.rb:16:in `unpack'
	/usr/local/bundle/gems/berkshelf-4.3.5/lib/berkshelf/community_rest.rb:102:in `download'
	/usr/local/bundle/gems/berkshelf-4.3.5/lib/berkshelf/downloader.rb:61:in `try_download'
	/usr/local/bundle/gems/berkshelf-4.3.5/lib/berkshelf/downloader.rb:35:in `block in download'
	/usr/local/bundle/gems/berkshelf-4.3.5/lib/berkshelf/downloader.rb:34:in `each'
	/usr/local/bundle/gems/berkshelf-4.3.5/lib/berkshelf/downloader.rb:34:in `download'
	/usr/local/bundle/gems/berkshelf-4.3.5/lib/berkshelf/installer.rb:105:in `install'
	/usr/local/bundle/gems/celluloid-0.16.0/lib/celluloid/calls.rb:26:in `public_send'
	/usr/local/bundle/gems/celluloid-0.16.0/lib/celluloid/calls.rb:26:in `dispatch'
	/usr/local/bundle/gems/celluloid-0.16.0/lib/celluloid/calls.rb:63:in `dispatch'
	/usr/local/bundle/gems/celluloid-0.16.0/lib/celluloid/cell.rb:60:in `block in invoke'
	/usr/local/bundle/gems/celluloid-0.16.0/lib/celluloid/cell.rb:71:in `block in task'
	/usr/local/bundle/gems/celluloid-0.16.0/lib/celluloid/actor.rb:357:in `block in task'
	/usr/local/bundle/gems/celluloid-0.16.0/lib/celluloid/tasks.rb:57:in `block in initialize'
	/usr/local/bundle/gems/celluloid-0.16.0/lib/celluloid/tasks/task_fiber.rb:15:in `block in create'
	(celluloid):0:in `remote procedure call'
	/usr/local/bundle/gems/celluloid-0.16.0/lib/celluloid/calls.rb:92:in `value'
	/usr/local/bundle/gems/celluloid-0.16.0/lib/celluloid/proxies/sync_proxy.rb:33:in `method_missing'
	/usr/local/bundle/gems/celluloid-0.16.0/lib/celluloid/proxies/cell_proxy.rb:17:in `_send_'
	/usr/local/bundle/gems/celluloid-0.16.0/lib/celluloid/pool_manager.rb:41:in `_send_'
	/usr/local/bundle/gems/celluloid-0.16.0/lib/celluloid/pool_manager.rb:140:in `method_missing'
	/usr/local/bundle/gems/celluloid-0.16.0/lib/celluloid/calls.rb:26:in `public_send'
	/usr/local/bundle/gems/celluloid-0.16.0/lib/celluloid/calls.rb:26:in `dispatch'
	/usr/local/bundle/gems/celluloid-0.16.0/lib/celluloid/calls.rb:63:in `dispatch'
	/usr/local/bundle/gems/celluloid-0.16.0/lib/celluloid/cell.rb:60:in `block in invoke'
	/usr/local/bundle/gems/celluloid-0.16.0/lib/celluloid/cell.rb:71:in `block in task'
	/usr/local/bundle/gems/celluloid-0.16.0/lib/celluloid/actor.rb:357:in `block in task'
	/usr/local/bundle/gems/celluloid-0.16.0/lib/celluloid/tasks.rb:57:in `block in initialize'
	/usr/local/bundle/gems/celluloid-0.16.0/lib/celluloid/tasks/task_fiber.rb:15:in `block in create'

An error occurred in a `before(:suite)` hook.
Failure/Error: raise Mixlib::Archive::TarError, "Unrecognized archive format" unless is_tar_archive?(file)

Mixlib::Archive::TarError:
  Unrecognized archive format
# /usr/local/bundle/gems/mixlib-archive-0.4.5/lib/mixlib/archive/tar.rb:138:in `reader'
# /usr/local/bundle/gems/mixlib-archive-0.4.5/lib/mixlib/archive/tar.rb:26:in `extract'
# /usr/local/bundle/gems/mixlib-archive-0.4.5/lib/mixlib/archive.rb:47:in `extract'
# /usr/local/bundle/gems/berkshelf-4.3.5/lib/berkshelf/community_rest.rb:16:in `unpack'
# /usr/local/bundle/gems/berkshelf-4.3.5/lib/berkshelf/community_rest.rb:102:in `download'
# /usr/local/bundle/gems/berkshelf-4.3.5/lib/berkshelf/downloader.rb:61:in `try_download'
# /usr/local/bundle/gems/berkshelf-4.3.5/lib/berkshelf/downloader.rb:35:in `block in download'
# /usr/local/bundle/gems/berkshelf-4.3.5/lib/berkshelf/downloader.rb:34:in `each'
# /usr/local/bundle/gems/berkshelf-4.3.5/lib/berkshelf/downloader.rb:34:in `download'
# /usr/local/bundle/gems/berkshelf-4.3.5/lib/berkshelf/installer.rb:105:in `install'
# /usr/local/bundle/gems/celluloid-0.16.0/lib/celluloid/calls.rb:26:in `public_send'
# /usr/local/bundle/gems/celluloid-0.16.0/lib/celluloid/calls.rb:26:in `dispatch'
# /usr/local/bundle/gems/celluloid-0.16.0/lib/celluloid/calls.rb:63:in `dispatch'
# /usr/local/bundle/gems/celluloid-0.16.0/lib/celluloid/cell.rb:60:in `block in invoke'
# /usr/local/bundle/gems/celluloid-0.16.0/lib/celluloid/cell.rb:71:in `block in task'
# /usr/local/bundle/gems/celluloid-0.16.0/lib/celluloid/actor.rb:357:in `block in task'
# /usr/local/bundle/gems/celluloid-0.16.0/lib/celluloid/tasks.rb:57:in `block in initialize'
# /usr/local/bundle/gems/celluloid-0.16.0/lib/celluloid/tasks/task_fiber.rb:15:in `block in create'
# (celluloid):0:in `remote procedure call'
# /usr/local/bundle/gems/celluloid-0.16.0/lib/celluloid/calls.rb:92:in `value'
# /usr/local/bundle/gems/celluloid-0.16.0/lib/celluloid/proxies/sync_proxy.rb:33:in `method_missing'
# /usr/local/bundle/gems/celluloid-0.16.0/lib/celluloid/proxies/cell_proxy.rb:17:in `_send_'
# /usr/local/bundle/gems/celluloid-0.16.0/lib/celluloid/pool_manager.rb:41:in `_send_'
# /usr/local/bundle/gems/celluloid-0.16.0/lib/celluloid/pool_manager.rb:140:in `method_missing'
# /usr/local/bundle/gems/celluloid-0.16.0/lib/celluloid/calls.rb:26:in `public_send'
# /usr/local/bundle/gems/celluloid-0.16.0/lib/celluloid/calls.rb:26:in `dispatch'
# /usr/local/bundle/gems/celluloid-0.16.0/lib/celluloid/calls.rb:63:in `dispatch'
# /usr/local/bundle/gems/celluloid-0.16.0/lib/celluloid/cell.rb:60:in `block in invoke'
# /usr/local/bundle/gems/celluloid-0.16.0/lib/celluloid/cell.rb:71:in `block in task'
# /usr/local/bundle/gems/celluloid-0.16.0/lib/celluloid/actor.rb:357:in `block in task'
# /usr/local/bundle/gems/celluloid-0.16.0/lib/celluloid/tasks.rb:57:in `block in initialize'
# /usr/local/bundle/gems/celluloid-0.16.0/lib/celluloid/tasks/task_fiber.rb:15:in `block in create'
# (celluloid):0:in `remote procedure call'
# /usr/local/bundle/gems/celluloid-0.16.0/lib/celluloid/future.rb:104:in `value'
# /usr/local/bundle/gems/celluloid-0.16.0/lib/celluloid/future.rb:68:in `value'
# /usr/local/bundle/gems/berkshelf-4.3.5/lib/berkshelf/installer.rb:134:in `map'
# /usr/local/bundle/gems/berkshelf-4.3.5/lib/berkshelf/installer.rb:134:in `install_from_lockfile'
# /usr/local/bundle/gems/berkshelf-4.3.5/lib/berkshelf/installer.rb:37:in `run'
# /usr/local/bundle/gems/berkshelf-4.3.5/lib/berkshelf/berksfile.rb:421:in `install'
# /usr/local/bundle/gems/berkshelf-4.3.5/lib/berkshelf/berksfile.rb:630:in `block in vendor'
# /usr/local/lib/ruby/2.3.0/tmpdir.rb:89:in `mktmpdir'
# /usr/local/bundle/gems/berkshelf-4.3.5/lib/berkshelf/berksfile.rb:628:in `vendor'
# /usr/local/bundle/gems/chefspec-5.4.0/lib/chefspec/berkshelf.rb:39:in `block in setup!'
# /usr/local/bundle/gems/thor-0.19.1/lib/thor/shell/basic.rb:20:in `mute'
# /usr/local/bundle/gems/chefspec-5.4.0/lib/chefspec/berkshelf.rb:35:in `setup!'
# /usr/local/lib/ruby/2.3.0/forwardable.rb:204:in `setup!'
# /usr/local/bundle/gems/chefspec-5.4.0/lib/chefspec/berkshelf.rb:61:in `block (2 levels) in <top (required)>'
# /usr/local/bundle/gems/rspec-core-3.7.1/lib/rspec/core/example.rb:447:in `instance_exec'
# /usr/local/bundle/gems/rspec-core-3.7.1/lib/rspec/core/example.rb:447:in `instance_exec'
# /usr/local/bundle/gems/rspec-core-3.7.1/lib/rspec/core/hooks.rb:350:in `run'
# /usr/local/bundle/gems/rspec-core-3.7.1/lib/rspec/core/configuration.rb:1981:in `block in run_suite_hooks'
# /usr/local/bundle/gems/rspec-core-3.7.1/lib/rspec/core/configuration.rb:1979:in `each'
# /usr/local/bundle/gems/rspec-core-3.7.1/lib/rspec/core/configuration.rb:1979:in `run_suite_hooks'
# /usr/local/bundle/gems/rspec-core-3.7.1/lib/rspec/core/configuration.rb:1925:in `with_suite_hooks'
# /usr/local/bundle/gems/rspec-core-3.7.1/lib/rspec/core/runner.rb:113:in `block in run_specs'
# /usr/local/bundle/gems/rspec-core-3.7.1/lib/rspec/core/reporter.rb:79:in `report'
# /usr/local/bundle/gems/rspec-core-3.7.1/lib/rspec/core/runner.rb:112:in `run_specs'
# /usr/local/bundle/gems/rspec-core-3.7.1/lib/rspec/core/runner.rb:87:in `run'
# /usr/local/bundle/gems/rspec-core-3.7.1/lib/rspec/core/runner.rb:71:in `run'
# /usr/local/bundle/gems/rspec-core-3.7.1/lib/rspec/core/runner.rb:45:in `invoke'
# /usr/local/bundle/gems/rspec-core-3.7.1/exe/rspec:4:in `<top (required)>'
# /usr/local/bundle/bin/rspec:29:in `load'
# /usr/local/bundle/bin/rspec:29:in `<top (required)>'
# /usr/local/lib/ruby/gems/2.3.0/gems/bundler-1.16.1/lib/bundler/cli/exec.rb:75:in `load'
# /usr/local/lib/ruby/gems/2.3.0/gems/bundler-1.16.1/lib/bundler/cli/exec.rb:75:in `kernel_load'
# /usr/local/lib/ruby/gems/2.3.0/gems/bundler-1.16.1/lib/bundler/cli/exec.rb:28:in `run'
# /usr/local/lib/ruby/gems/2.3.0/gems/bundler-1.16.1/lib/bundler/cli.rb:424:in `exec'
# /usr/local/lib/ruby/gems/2.3.0/gems/bundler-1.16.1/lib/bundler/vendor/thor/lib/thor/command.rb:27:in `run'
# /usr/local/lib/ruby/gems/2.3.0/gems/bundler-1.16.1/lib/bundler/vendor/thor/lib/thor/invocation.rb:126:in `invoke_command'
# /usr/local/lib/ruby/gems/2.3.0/gems/bundler-1.16.1/lib/bundler/vendor/thor/lib/thor.rb:387:in `dispatch'
# /usr/local/lib/ruby/gems/2.3.0/gems/bundler-1.16.1/lib/bundler/cli.rb:27:in `dispatch'
# /usr/local/lib/ruby/gems/2.3.0/gems/bundler-1.16.1/lib/bundler/vendor/thor/lib/thor/base.rb:466:in `start'
# /usr/local/lib/ruby/gems/2.3.0/gems/bundler-1.16.1/lib/bundler/cli.rb:18:in `start'
# /usr/local/lib/ruby/gems/2.3.0/gems/bundler-1.16.1/exe/bundle:30:in `block in <top (required)>'
# /usr/local/lib/ruby/gems/2.3.0/gems/bundler-1.16.1/lib/bundler/friendly_errors.rb:122:in `with_friendly_errors'
# /usr/local/lib/ruby/gems/2.3.0/gems/bundler-1.16.1/exe/bundle:22:in `<top (required)>'
# /usr/local/bundle/bin/bundle:104:in `load'
# /usr/local/bundle/bin/bundle:104:in `<main>'
Installing iptables (4.3.4)

**Comment by spion06** [comment]
One that works (used yum 5.1.0)
```
$ curl -L https://supermarket.chef.io/api/v1/cookbooks/yum/versions/5.1.0/download | gunzip > test1.tar
irb(main):001:0> File.read('test1.tar')[257..262]
=> "ustar\u0000"
```

One that does not work (used cerner_splunk )
```
$ curl -L https://supermarket.chef.io/api/v1/cookbooks/cerner_splunk/versions/2.12.0/download | gunzip > test2.tar
irb(main):001:0> File.read('test2.tar')[257..262]
=> "ustar "
```

Seems that the check for a null byte is not always the correct check.

**Comment by spion06** [comment]
i took a stab at this on #21

**Comment by gsdevme** [comment]
Seeing the same thing with Berkshelf 6, `gem 'mixlib-archive', '< 0.4.5'` resolved it short term

**Comment by lehn-etracker** [comment]
I had the same error today. Executing `bundle update` to get latest (0.4.6) version of `mixlib-archive` gem fixed it for me.
