### ISSUE TITLE
README doesn't suggest installing ffi-libarchive

### ISSUE THREAD

**Issue by agrare** [chef/mixlib-archive#45]
### Describe the Enhancement:
We recently switched over to using mixlib-archive and it has been great.  We recently ran into a weird issue where files were mysteriously being dropped from our extracted archives, turned out it was a filename length issue.

We discovered that Mixlib::Archive was falling back to Tar because `require "mixlib/archive/lib_archive"` was failing without the `ffi-libarchive` gem installed.

It would be great if it could be mentioned in the README that ffi-libarchive enhances the behavior of Mixlib::Archive.

Thanks!

**Comment by tas50** [comment]
Yep that's a problem. I added it to https://github.com/chef/mixlib-archive/pull/58
