### ISSUE TITLE
Versions 1.0.2 and 1.0.3 are not available on rubygems.

### ISSUE THREAD

**Issue by uthark** [chef/mixlib-archive#46]
# Version:

Tried to install 1.0.3.

# Environment:

# Scenario:

Tried to install 1.0.3.
Failed.

```
bundle update mixlib-archive
Fetching gem metadata from https://rubygems.org/.......
Fetching gem metadata from https://rubygems.org/.
Could not find gem 'mixlib-archive (~> 1.0.3)' in any of the gem sources listed in your Gemfile.
```

# Steps to Reproduce:

Require version 1.0.2 or 1.0.3.

# Expected Result:

gem is installed.

# Actual Result:

Error returned. https://rubygems.org/gems/mixlib-archive also doesn't list versions here, but there are such versions here: https://github.com/chef/mixlib-archive/releases

**Comment by tas50** [comment]
This is by design. Every PR merge builds the gem and pushes it to our internal artifactory server. When we promote to stable we update the changelog and push that version to rubygems. If you check the changelog it says those changes aren't yet on rubygems. It was just some rubocopfixes.
